version: '3.9'

services:
  sgil-proveedores-service:
    build: .
    ports:
      - "8090:8090"
    environment:
      - DB_HOST_URL=postgres-monitoreo
      - DB_NAME=sgil-monitoreo
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - PROMETHEUS_MULTIPROC_DIR=/tmp
    depends_on:
      postgres-monitoreo:
        condition: service_healthy

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/logs/health"]  # Ajusta la URL si es necesario
      interval: 30s
      timeout: 10s
      retries: 5

  postgres-monitoreo:
    image: postgres:15-alpine
    container_name: postgres-monitoreo
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sgil-monitoreo
    ports:
      - "5490:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 20s
      retries: 5


volumes:
  pg_data:


  