global:
  scrape_interval: 15s  # Scrape metrics every 15 seconds

scrape_configs:

  - job_name: "pm_sgil-monitoreo-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["sgil-monitoreo-service:8090"]

